name: postgres-db

services:
  postgres:
    image: postgres:16
    container_name: walurl-postgres-db
    restart: on-failure
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: walurl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data