"""update the url model id from integer to string and to have a uuid4 as its default value

Revision ID: 461cdea154d6
Revises: 6bb28afc2d91
Create Date: 2026-08-17 18:43:54.408090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461cdea154d6'
down_revision: Union[str, Sequence[str], None] = '6bb28afc2d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    op.alter_column('urls', 'id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
